path: generation
train: images/train
val: images/val
test: images/test/1.0_90.0
names:
  0: ace
  1: two
  2: three
  3: four
  4: five
  5: six
  6: seven
  7: eight
  8: nine
  9: ten
  10: jack
  11: queen
  12: king